// Code generated by ent, DO NOT EDIT.

package memory

import (
	"stella/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldUserID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldContent, v))
}

// LastAccessedAt applies equality check predicate on the "last_accessed_at" field. It's identical to LastAccessedAtEQ.
func LastAccessedAt(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldLastAccessedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContainsFold(FieldUserID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContainsFold(FieldContent, v))
}

// LastAccessedAtEQ applies the EQ predicate on the "last_accessed_at" field.
func LastAccessedAtEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldLastAccessedAt, v))
}

// LastAccessedAtNEQ applies the NEQ predicate on the "last_accessed_at" field.
func LastAccessedAtNEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldLastAccessedAt, v))
}

// LastAccessedAtIn applies the In predicate on the "last_accessed_at" field.
func LastAccessedAtIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldLastAccessedAt, vs...))
}

// LastAccessedAtNotIn applies the NotIn predicate on the "last_accessed_at" field.
func LastAccessedAtNotIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldLastAccessedAt, vs...))
}

// LastAccessedAtGT applies the GT predicate on the "last_accessed_at" field.
func LastAccessedAtGT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldLastAccessedAt, v))
}

// LastAccessedAtGTE applies the GTE predicate on the "last_accessed_at" field.
func LastAccessedAtGTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldLastAccessedAt, v))
}

// LastAccessedAtLT applies the LT predicate on the "last_accessed_at" field.
func LastAccessedAtLT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldLastAccessedAt, v))
}

// LastAccessedAtLTE applies the LTE predicate on the "last_accessed_at" field.
func LastAccessedAtLTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldLastAccessedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Memory {
	return predicate.Memory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Memory {
	return predicate.Memory(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Memory) predicate.Memory {
	return predicate.Memory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Memory) predicate.Memory {
	return predicate.Memory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Memory) predicate.Memory {
	return predicate.Memory(sql.NotPredicates(p))
}
