// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stella/ent/memory"
	"stella/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryCreate is the builder for creating a Memory entity.
type MemoryCreate struct {
	config
	mutation *MemoryMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *MemoryCreate) SetUserID(v string) *MemoryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *MemoryCreate) SetContent(v string) *MemoryCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetVector sets the "vector" field.
func (_c *MemoryCreate) SetVector(v []float32) *MemoryCreate {
	_c.mutation.SetVector(v)
	return _c
}

// SetLastAccessedAt sets the "last_accessed_at" field.
func (_c *MemoryCreate) SetLastAccessedAt(v time.Time) *MemoryCreate {
	_c.mutation.SetLastAccessedAt(v)
	return _c
}

// SetNillableLastAccessedAt sets the "last_accessed_at" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableLastAccessedAt(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetLastAccessedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemoryCreate) SetCreatedAt(v time.Time) *MemoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableCreatedAt(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *MemoryCreate) SetUser(v *User) *MemoryCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the MemoryMutation object of the builder.
func (_c *MemoryCreate) Mutation() *MemoryMutation {
	return _c.mutation
}

// Save creates the Memory in the database.
func (_c *MemoryCreate) Save(ctx context.Context) (*Memory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryCreate) SaveX(ctx context.Context) *Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryCreate) defaults() {
	if _, ok := _c.mutation.LastAccessedAt(); !ok {
		v := memory.DefaultLastAccessedAt()
		_c.mutation.SetLastAccessedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Memory.user_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Memory.content"`)}
	}
	if _, ok := _c.mutation.Vector(); !ok {
		return &ValidationError{Name: "vector", err: errors.New(`ent: missing required field "Memory.vector"`)}
	}
	if _, ok := _c.mutation.LastAccessedAt(); !ok {
		return &ValidationError{Name: "last_accessed_at", err: errors.New(`ent: missing required field "Memory.last_accessed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Memory.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Memory.user"`)}
	}
	return nil
}

func (_c *MemoryCreate) sqlSave(ctx context.Context) (*Memory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryCreate) createSpec() (*Memory, *sqlgraph.CreateSpec) {
	var (
		_node = &Memory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memory.Table, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(memory.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Vector(); ok {
		_spec.SetField(memory.FieldVector, field.TypeJSON, value)
		_node.Vector = value
	}
	if value, ok := _c.mutation.LastAccessedAt(); ok {
		_spec.SetField(memory.FieldLastAccessedAt, field.TypeTime, value)
		_node.LastAccessedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memory.UserTable,
			Columns: []string{memory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemoryCreateBulk is the builder for creating many Memory entities in bulk.
type MemoryCreateBulk struct {
	config
	err      error
	builders []*MemoryCreate
}

// Save creates the Memory entities in the database.
func (_c *MemoryCreateBulk) Save(ctx context.Context) ([]*Memory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Memory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryCreateBulk) SaveX(ctx context.Context) []*Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
