// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stella/ent/message"
	"stella/ent/session"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *MessageCreate) SetSessionID(v string) *MessageCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MessageCreate) SetUserID(v string) *MessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *MessageCreate) SetNillableUserID(v *string) *MessageCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *MessageCreate) SetRole(v string) *MessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetType sets the "type" field.
func (_c *MessageCreate) SetType(v string) *MessageCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *MessageCreate) SetContent(v string) *MessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetToolCalls sets the "tool_calls" field.
func (_c *MessageCreate) SetToolCalls(v string) *MessageCreate {
	_c.mutation.SetToolCalls(v)
	return _c
}

// SetNillableToolCalls sets the "tool_calls" field if the given value is not nil.
func (_c *MessageCreate) SetNillableToolCalls(v *string) *MessageCreate {
	if v != nil {
		_c.SetToolCalls(*v)
	}
	return _c
}

// SetToolID sets the "tool_id" field.
func (_c *MessageCreate) SetToolID(v string) *MessageCreate {
	_c.mutation.SetToolID(v)
	return _c
}

// SetNillableToolID sets the "tool_id" field if the given value is not nil.
func (_c *MessageCreate) SetNillableToolID(v *string) *MessageCreate {
	if v != nil {
		_c.SetToolID(*v)
	}
	return _c
}

// SetData sets the "data" field.
func (_c *MessageCreate) SetData(v []byte) *MessageCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MessageCreate) SetCreatedAt(v time.Time) *MessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MessageCreate) SetNillableCreatedAt(v *time.Time) *MessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the Session entity.
func (_c *MessageCreate) SetSession(v *Session) *MessageCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_c *MessageCreate) Mutation() *MessageMutation {
	return _c.mutation
}

// Save creates the Message in the database.
func (_c *MessageCreate) Save(ctx context.Context) (*Message, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageCreate) defaults() {
	if _, ok := _c.mutation.ToolCalls(); !ok {
		v := message.DefaultToolCalls
		_c.mutation.SetToolCalls(v)
	}
	if _, ok := _c.mutation.ToolID(); !ok {
		v := message.DefaultToolID
		_c.mutation.SetToolID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := message.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Message.session_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Message.role"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Message.type"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Message.content"`)}
	}
	if _, ok := _c.mutation.ToolCalls(); !ok {
		return &ValidationError{Name: "tool_calls", err: errors.New(`ent: missing required field "Message.tool_calls"`)}
	}
	if _, ok := _c.mutation.ToolID(); !ok {
		return &ValidationError{Name: "tool_id", err: errors.New(`ent: missing required field "Message.tool_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Message.created_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Message.session"`)}
	}
	return nil
}

func (_c *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(message.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(message.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ToolCalls(); ok {
		_spec.SetField(message.FieldToolCalls, field.TypeString, value)
		_node.ToolCalls = value
	}
	if value, ok := _c.mutation.ToolID(); ok {
		_spec.SetField(message.FieldToolID, field.TypeString, value)
		_node.ToolID = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(message.FieldData, field.TypeBytes, value)
		_node.Data = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.SessionTable,
			Columns: []string{message.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	err      error
	builders []*MessageCreate
}

// Save creates the Message entities in the database.
func (_c *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Message, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
