// Code generated by ent, DO NOT EDIT.

package ent

import (
	"stella/ent/memory"
	"stella/ent/message"
	"stella/ent/schema"
	"stella/ent/session"
	"stella/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memoryFields := schema.Memory{}.Fields()
	_ = memoryFields
	// memoryDescLastAccessedAt is the schema descriptor for last_accessed_at field.
	memoryDescLastAccessedAt := memoryFields[3].Descriptor()
	// memory.DefaultLastAccessedAt holds the default value on creation for the last_accessed_at field.
	memory.DefaultLastAccessedAt = memoryDescLastAccessedAt.Default.(func() time.Time)
	// memory.UpdateDefaultLastAccessedAt holds the default value on update for the last_accessed_at field.
	memory.UpdateDefaultLastAccessedAt = memoryDescLastAccessedAt.UpdateDefault.(func() time.Time)
	// memoryDescCreatedAt is the schema descriptor for created_at field.
	memoryDescCreatedAt := memoryFields[4].Descriptor()
	// memory.DefaultCreatedAt holds the default value on creation for the created_at field.
	memory.DefaultCreatedAt = memoryDescCreatedAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescToolCalls is the schema descriptor for tool_calls field.
	messageDescToolCalls := messageFields[5].Descriptor()
	// message.DefaultToolCalls holds the default value on creation for the tool_calls field.
	message.DefaultToolCalls = messageDescToolCalls.Default.(string)
	// messageDescToolID is the schema descriptor for tool_id field.
	messageDescToolID := messageFields[6].Descriptor()
	// message.DefaultToolID holds the default value on creation for the tool_id field.
	message.DefaultToolID = messageDescToolID.Default.(string)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[8].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTitle is the schema descriptor for title field.
	sessionDescTitle := sessionFields[3].Descriptor()
	// session.DefaultTitle holds the default value on creation for the title field.
	session.DefaultTitle = sessionDescTitle.Default.(string)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[4].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[5].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
