// Code generated by ent, DO NOT EDIT.

package user

import (
	"stella/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldID, id))
}

// Qq applies equality check predicate on the "qq" field. It's identical to QqEQ.
func Qq(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldQq, v))
}

// QqID applies equality check predicate on the "qq_id" field. It's identical to QqIDEQ.
func QqID(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldQqID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// QqEQ applies the EQ predicate on the "qq" field.
func QqEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldQq, v))
}

// QqNEQ applies the NEQ predicate on the "qq" field.
func QqNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldQq, v))
}

// QqIn applies the In predicate on the "qq" field.
func QqIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldQq, vs...))
}

// QqNotIn applies the NotIn predicate on the "qq" field.
func QqNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldQq, vs...))
}

// QqGT applies the GT predicate on the "qq" field.
func QqGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldQq, v))
}

// QqGTE applies the GTE predicate on the "qq" field.
func QqGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldQq, v))
}

// QqLT applies the LT predicate on the "qq" field.
func QqLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldQq, v))
}

// QqLTE applies the LTE predicate on the "qq" field.
func QqLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldQq, v))
}

// QqContains applies the Contains predicate on the "qq" field.
func QqContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldQq, v))
}

// QqHasPrefix applies the HasPrefix predicate on the "qq" field.
func QqHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldQq, v))
}

// QqHasSuffix applies the HasSuffix predicate on the "qq" field.
func QqHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldQq, v))
}

// QqEqualFold applies the EqualFold predicate on the "qq" field.
func QqEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldQq, v))
}

// QqContainsFold applies the ContainsFold predicate on the "qq" field.
func QqContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldQq, v))
}

// QqIDEQ applies the EQ predicate on the "qq_id" field.
func QqIDEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldQqID, v))
}

// QqIDNEQ applies the NEQ predicate on the "qq_id" field.
func QqIDNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldQqID, v))
}

// QqIDIn applies the In predicate on the "qq_id" field.
func QqIDIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldQqID, vs...))
}

// QqIDNotIn applies the NotIn predicate on the "qq_id" field.
func QqIDNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldQqID, vs...))
}

// QqIDGT applies the GT predicate on the "qq_id" field.
func QqIDGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldQqID, v))
}

// QqIDGTE applies the GTE predicate on the "qq_id" field.
func QqIDGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldQqID, v))
}

// QqIDLT applies the LT predicate on the "qq_id" field.
func QqIDLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldQqID, v))
}

// QqIDLTE applies the LTE predicate on the "qq_id" field.
func QqIDLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldQqID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.Session) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMemories applies the HasEdge predicate on the "memories" edge.
func HasMemories() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MemoriesTable, MemoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemoriesWith applies the HasEdge predicate on the "memories" edge with a given conditions (other predicates).
func HasMemoriesWith(preds ...predicate.Memory) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMemoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
